# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
run_clonal_origin <- function(argv_list) {
    .Call(`_RClonOr_run_clonal_origin`, argv_list)
}

